# Generated by Django 3.2.12 on 2022-09-08 19:32

import apps.profiles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(blank=True, max_length=48)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('img_profile', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.rename_img, verbose_name='photo de profile')),
                ('img_bg', models.ImageField(blank=True, null=True, upload_to=apps.profiles.models.rename_img, verbose_name='photo de couverture')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissence')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=15, verbose_name='sexe')),
                ('phone', models.CharField(blank=True, max_length=24, verbose_name='téléphone')),
                ('adress', models.CharField(blank=True, max_length=128, verbose_name='adresse')),
                ('town', models.CharField(blank=True, max_length=68, verbose_name='ville')),
                ('zipcode', models.CharField(blank=True, max_length=22, verbose_name='code postal')),
                ('country', models.CharField(blank=True, max_length=45, verbose_name='pays')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('link_linkedin', models.URLField(blank=True, verbose_name='lien de votre profile linkedin')),
                ('link_gitthub', models.URLField(blank=True, verbose_name='lien de votre profile gitthub')),
                ('link_twitter', models.URLField(blank=True, verbose_name='lien de votre twitter')),
                ('link_mysite', models.URLField(blank=True, verbose_name='lien de votre de site web')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
